<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Vido.Core</RootNamespace>
    <Version>$(VidoVersion)</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="$(SkiaSharpVersion)" />
  </ItemGroup>

</Project>
