<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Vido.ViewModels</RootNamespace>
    <Version>$(VidoVersion)</Version>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Vido.Tests" />
    <InternalsVisibleTo Include="Vido.Views" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="$(CommunityToolkitMvvmVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vido.Core\Vido.Core.csproj" />
    <ProjectReference Include="..\Vido.Services\Vido.Services.csproj" />
  </ItemGroup>

</Project>
