<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Vido.Services</RootNamespace>
    <Version>$(VidoVersion)</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Vido.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vido.Core\Vido.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FFmpeg.AutoGen.Abstractions" Version="$(FFmpegAutoGenVersion)" />
    <PackageReference Include="FFmpeg.AutoGen.Bindings.DynamicallyLoaded" Version="$(FFmpegAutoGenVersion)" />
    <PackageReference Include="FFmpeg.LGPL" Version="$(FFmpegLGPLVersion)" />
    <PackageReference Include="NAudio" Version="$(NAudioVersion)" />
  </ItemGroup>

</Project>
