<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>Vido.Views</RootNamespace>
    <Version>$(VidoVersion)</Version>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\Vido.png" />
    <Resource Include="Assets\video-file-icon.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vido.Core\Vido.Core.csproj" />
    <ProjectReference Include="..\Vido.ViewModels\Vido.ViewModels.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Markdig" Version="$(MarkdigVersion)" />
  </ItemGroup>

</Project>
