<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>Vido.Views</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\Vido.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vido.Core\Vido.Core.csproj" />
    <ProjectReference Include="..\Vido.ViewModels\Vido.ViewModels.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Markdig" Version="0.38.0" />
  </ItemGroup>

</Project>
