<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>Vido.Views</RootNamespace>
    <Version>$(VidoVersion)</Version>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\Vido.png" />
    <Resource Include="Assets\video-file-icon.png" />
    <Resource Include="Assets\Osr2Plus\connect-dot-green.png" />
    <Resource Include="Assets\Osr2Plus\connect-dot-red.png" />
    <Resource Include="Assets\Osr2Plus\connect-icon.png" />
    <Resource Include="Assets\Osr2Plus\funscript-pitch.png" />
    <Resource Include="Assets\Osr2Plus\funscript-roll.png" />
    <Resource Include="Assets\Osr2Plus\funscript-stroke.png" />
    <Resource Include="Assets\Osr2Plus\funscript-twist.png" />
    <Resource Include="Assets\Osr2Plus\sidebar-icon.png" />
    <Resource Include="Assets\Pulse\Pulse-plugin.png" />
    <Resource Include="Assets\Pulse\sidebar-icon.png" />
    <Resource Include="Assets\Playlists\Playlist-plugin.png" />
    <Resource Include="Assets\Playlists\sidebar-icon.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vido.Core\Vido.Core.csproj" />
    <ProjectReference Include="..\Vido.Services\Vido.Services.csproj" />
    <ProjectReference Include="..\Vido.ViewModels\Vido.ViewModels.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Markdig" Version="$(MarkdigVersion)" />
    <PackageReference Include="SkiaSharp.Views.WPF" Version="$(SkiaSharpViewsWpfVersion)" />
  </ItemGroup>

</Project>
